name: Modelops deploy
on:
 push:
  branches: [master]
 pull_request:
  branches: [master]
 repository_dispatch:
  types: [ml_ci_cd]
jobs:
 ml_ci_cd:
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v2
  - name: python version
    run: python --version
  - name: pip install
    run: pip install -r requirements.txt
  - name: download dataset
    run: wget -O data/heart-disease.csv ${{github.event.client_payload.dataseturl}}
  - name: cat dataset
    run: cat data/heart-disease.csv
  - name: train model
    run: python model/train.py
  - name: Debugging step
    run: echo "DOCKER_USER=${{secrets.DOCKER_USER}} MODEL_NAME=${{secrets.MODEL_NAME}} SHA=${{github.event.client_payload.sha}}"
  - name: docker build
    if: ${{ github.event.client_payload.sha != '' }}
    run: docker build -t ${{secrets.DOCKER_USER}}/${{secrets.MODEL_NAME}}:${{github.event.client_payload.sha}} .

  - name: docker build with modelname
    if: ${{ github.event.client_payload.sha == '' }}
    run: docker build -t ${{secrets.DOCKER_USER}}/${{secrets.MODEL_NAME}}:latest .

  - name: docker login
    env:
      DOCKER_USER: ${{secrets.DOCKER_USER}}
      DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
    run: |
      docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
  - name: docker Push
    run: docker push ${{secrets.DOCKER_USER}}/${{secrets.MODEL_NAME}}:${{ github.event.client_payload.sha }}
  - name: show images
    run: docker images
